name: Build and Push Container

on:
  workflow_call:
    inputs:
      container_name:
        required: true
        type: string
      platforms:
        type: string
        default: linux/amd64,linux/arm64

jobs:
  build:
    runs-on: ubuntu-latest
    if: "${{ !contains(github.event.head_commit.message, 'ci skip') }}"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Github CR Login
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Date
        run: echo "DATE_TAG=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

      - name: Build Container
        uses: docker/build-push-action@v6
        with:
          # avoid https://github.com/docker/build-push-action#git-context
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/bellflight/avr/${{ inputs.container_name }}:latest
            ghcr.io/bellflight/avr/${{ inputs.container_name }}:${{ env.DATE_TAG }}
          platforms: ${{ inputs.platforms }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
