name: Pre-Commit Update

on:
  workflow_call:
    inputs:
      target_branch:
        type: string
        default: develop


jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.target_branch }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install pre-commit-update
        run: pipx install pre-commit-update

      - name: Run pre-commit-update
        run: pre-commit-update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ github.token }}
          branch: update/pre-commit-update
          title: Update Pre-Commit hooks for ${{ github.repository }}
          commit-message: Update Pre-Commit hooks
          delete-branch: true
          body: |
            Update versions of tools in pre-commit configs to latest version.
            Please verify the changes locally, as a pull request created by GitHub Actions cannot trigger workflows:

            ```bash
            git fetch
            git checkout update/pre-commit-update
            git pull
            vtr pre-commit
            ```
          labels: dependencies
